/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.xtext.example.mydsl.myDsl.Nutzen;
import org.xtext.example.mydsl.myDsl.Rolle;
import org.xtext.example.mydsl.myDsl.Title;
import org.xtext.example.mydsl.myDsl.User_Story;
import org.xtext.example.mydsl.myDsl.Ziel_Wunsch;
/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class MyDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public MyDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
 
	// Labels and icons can be computed like this:
	String text(User_Story ele) {
		return "User Story : " + ele.getTitle().getSubstantiv() + " " + ele.getTitle().getInfinitiv();
	}
 
	String text(Title ele) {
		return "Title : " + ele.getSubstantiv() + " " + ele.getInfinitiv();
	}
	
	String text(Rolle ele) {
		return "Rolle : " + ele.getSubstantiv();
	}
	String text(Nutzen ele) {
		String inf = ele.getVerb().replaceFirst("zu", "");
		return "Nutzen : " + ele.getSubject() + " "+ inf;
	}
	String text(Ziel_Wunsch ele) {
		return "Ziel und Wunsch : " + ele.getSubject() + " "+ ele.getInfinitiv();
	}

}