/**
 * generated by Xtext 2.34.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Title;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Title</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.TitleImpl#getSubstantiv <em>Substantiv</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.TitleImpl#getInfinitiv <em>Infinitiv</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TitleImpl extends MinimalEObjectImpl.Container implements Title
{
  /**
   * The default value of the '{@link #getSubstantiv() <em>Substantiv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubstantiv()
   * @generated
   * @ordered
   */
  protected static final String SUBSTANTIV_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSubstantiv() <em>Substantiv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubstantiv()
   * @generated
   * @ordered
   */
  protected String substantiv = SUBSTANTIV_EDEFAULT;

  /**
   * The default value of the '{@link #getInfinitiv() <em>Infinitiv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInfinitiv()
   * @generated
   * @ordered
   */
  protected static final String INFINITIV_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInfinitiv() <em>Infinitiv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInfinitiv()
   * @generated
   * @ordered
   */
  protected String infinitiv = INFINITIV_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TitleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TITLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSubstantiv()
  {
    return substantiv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubstantiv(String newSubstantiv)
  {
    String oldSubstantiv = substantiv;
    substantiv = newSubstantiv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.TITLE__SUBSTANTIV, oldSubstantiv, substantiv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInfinitiv()
  {
    return infinitiv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInfinitiv(String newInfinitiv)
  {
    String oldInfinitiv = infinitiv;
    infinitiv = newInfinitiv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.TITLE__INFINITIV, oldInfinitiv, infinitiv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.TITLE__SUBSTANTIV:
        return getSubstantiv();
      case MyDslPackage.TITLE__INFINITIV:
        return getInfinitiv();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.TITLE__SUBSTANTIV:
        setSubstantiv((String)newValue);
        return;
      case MyDslPackage.TITLE__INFINITIV:
        setInfinitiv((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TITLE__SUBSTANTIV:
        setSubstantiv(SUBSTANTIV_EDEFAULT);
        return;
      case MyDslPackage.TITLE__INFINITIV:
        setInfinitiv(INFINITIV_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TITLE__SUBSTANTIV:
        return SUBSTANTIV_EDEFAULT == null ? substantiv != null : !SUBSTANTIV_EDEFAULT.equals(substantiv);
      case MyDslPackage.TITLE__INFINITIV:
        return INFINITIV_EDEFAULT == null ? infinitiv != null : !INFINITIV_EDEFAULT.equals(infinitiv);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (substantiv: ");
    result.append(substantiv);
    result.append(", infinitiv: ");
    result.append(infinitiv);
    result.append(')');
    return result.toString();
  }

} //TitleImpl
